import { ReactNode } from 'react';
import { GlobalContextProvider } from './context'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
interface RootLayoutProps {
  children: ReactNode;
}
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <GlobalContextProvider>
        {children}
        </GlobalContextProvider> </body>
    </html>
  )
}
